// src/i18n/en.ts — English strings (source of truth for all locales)

import type { Translations } from "./types";

const en: Translations = {
  // Autopilot
  "autopilot.clickToStop": "Autopilot ON — click to stop",
  "autopilot.ariaCancel": "Autopilot active — click to cancel",

  // Audio
  "audio.mute": "Mute",
  "audio.unmute": "Unmute",

  // Toolbar
  "toolbar.restart": "Restart",
  "toolbar.screenshot": "Screenshot",
  "toolbar.showSolve": "Show how to solve this question",
  "toolbar.share": "Share",
  "toolbar.comments": "Comments",
  "toolbar.addComment": "+ Add Comment",

  // Level buttons
  "level.completePrev": "Complete Level {n} first",

  // Session report modal
  "report.shareReport": "Share Report",
  "report.creating": "Creating...",
  "report.nextLevel": "Next Level",
  "report.playAgain": "Play Again",
  "report.emailAria": "Email report",
  "report.sendTitle": "Send the report by email",
  "report.enterEmail": "Enter an email address",
  "report.emailPlaceholder": "parent@example.com",
  "report.namePlaceholder": "Your name",
  "report.subheading": "Monster Round Crushed!",
  "report.score": "Score",
  "report.accuracy": "Accuracy",
  "report.eggs": "Eggs",
  "report.sendSuccess": "Report sent to {email}",
  "report.sendFail": "Failed to send report.",

  // Game
  "game.correct": "Correct! 🎉",
  "game.wrongAnswer": "The answer was {answer}",
  "game.tryOnYourOwn": "Try on your own",
  "game.tapAnywhere": "Tap anywhere to start",
  "game.dragDino": "Drag the dinosaur along the trail",
  "game.enterDistance": "Enter the distance",
  "game.monsterRoundStart": "Monster Round!",
  "game.monsterRoundHint": "No odometer — solve it in your head!",
  "game.howMuchFarther": "How much farther?",
  "game.tryAgain": "Try again!",
  "game.typeNumber": "Type a number!",
  "game.enterNumber": "Enter a number!",
  "game.touchAndDrag": "Touch and Drag",
  "game.clickAndDrag": "Click and Drag",
  "game.enterValue": "Enter the Value",
  "game.collectGoldenEggs": "Collect {count} Golden Eggs ✨",
  "game.youDidIt": "You Did It!",
  "game.allMastered": "All 3 Levels Mastered",
  "game.everyMonsterRound": "Including every Monster Round!",
  "game.levelClear": "Level {level} Clear!",
  "game.allEggsCollected": "All {count} eggs collected!",
  "game.monsterCrushed": "Monster Round Crushed!",

  // Rotate prompt
  "rotate.heading": "Rotate your device",
  "rotate.subtext": "This game plays best in landscape mode",

  // Social
  "social.shareTitle": "Play Distance Calculator — a free maths game!",
  "social.commentsTitle": "Comments",

  // PDF report
  "pdf.title": "Distance Calculator",
  "pdf.sessionReport": "Level {n} Session Report",
  "pdf.gameDescription": "About This Game",
  "pdf.objectiveLabel": "Objective:",
  "pdf.objectiveLevel1": "Drag the dinosaur and add the segment distances to find the total journey.",
  "pdf.objectiveLevel2": "The total is given. Find the missing segment distance by subtracting.",
  "pdf.objectiveLevel3": "Compare two distances from a shared hub and find the difference.",
  "pdf.scoreLabel": "Score",
  "pdf.accuracyLabel": "Accuracy",
  "pdf.timeLabel": "Total Time",
  "pdf.questionLabel": "Q{n}",
  "pdf.correct": "CORRECT",
  "pdf.wrong": "WRONG",
  "pdf.givenAnswer": "Your answer: {value}",
  "pdf.correctAnswer": "Correct answer: {value}",
  "pdf.encourage90": "Outstanding work! 🌟",
  "pdf.encourage70": "Great effort! Keep it up! 🎉",
  "pdf.encourage50": "Good try! Practice makes perfect! 💪",
  "pdf.encourageBelow": "Keep going — you're learning! 🌱",
  "pdf.tip": "Tip: Go back and try the questions you missed.",
  "pdf.footer": "Generated by SeeMaths",
  "pdf.footerUrl": "www.seemaths.com",
  "pdf.durationMin": "m",
  "pdf.durationSec": "s",
  "pdf.nswCurriculum": "NSW Mathematics Curriculum",
  "pdf.basicRound": "Basic Round:",
  "pdf.basicRoundDesc": "Earn 10 eggs by answering trail distance questions. One new map per question.",
  "pdf.monsterRoundLabel": "Monster Round:",
  "pdf.monsterRoundDesc": "Defend all 10 eggs against harder questions. Wrong answers lose an egg.",
  "pdf.monsterBadge": "MONSTER",
  "pdf.answered": "answered {value}",
  "pdf.correctIn": "(correct: {value})",
  "pdf.tipAreas": "Tip: Try practising {areas} next time!",
  "pdf.areaAddingDistances": "adding distances",
  "pdf.areaFindingMissing": "finding missing distances",
  "pdf.areaComparingDistances": "comparing distances",

  // Question prompt templates
  "game.prompt.l1TwoStop": "{dino} wants to go from {from} to {to}. How far should {dino} travel?",
  "game.prompt.l1MultiStop": "{dino} goes from {stops}. How far should {dino} travel in total?",
  "game.prompt.l2MissingLeg": "The total distance from {from} to {to} is {total} {unit}. What is the missing distance from {hidFrom} to {hidTo}?",
  "game.prompt.l3HowMuchFarther": "From {hub}, how much farther is it to {far} than to {near}?",
  "game.prompt.l3SubFromTo": "How far is it from {from} to {to}?",
  "game.stopSeparator": " → ",

  // Email
  "email.subject": "{gameName} Report",
  "email.greeting": "Hi there,",
  "email.bodyIntro": "{playerName} played {game} at {time} on {date} for {duration}. Score: {score}, Accuracy: {accuracy}.",
  "email.curriculumIntro": "This game covers {stageLabel}:",
  "email.regards": "Regards,",
  "email.invalidEmail": "Please enter a valid email address.",
  "email.missingPdf": "Report attachment is missing.",
  "email.notConfigured": "Email service is not configured.",
  "email.sendFailed": "Failed to send report.",

  // Curriculum
  "curriculum.stageLabel": "Stage 3 (Years 5–6)",
  "curriculum.descL1L2": "Compares, orders and calculates with fractions, decimals and percentages.",
  "curriculum.descL3": "Selects and uses appropriate unit and device to measure lengths and distances, calculates perimeters, and converts between units of length.",

  // Language switcher
  "lang.label": "Language",
  "lang.en": "English",
  "lang.zh": "中文",
  "lang.hi": "हिन्दी",
  "lang.other": "Other...",
  "lang.translating": "Translating...",
  "lang.translateFail": "Translation failed. Please try again.",
  "lang.promptTitle": "Translate to another language",
  "lang.promptPlaceholder": "e.g. French, Arabic, Hindi...",
  "lang.translate": "Translate",
  "lang.cancel": "Cancel",
};

export default en;
